### PR TITLE
fix: prevent deprecation errors in php 8.1+

### LINKED ISSUE #2930: Deprecation errors in PHP8.1+
Deprecation errors are thrown in PHP8.1+. I will prepare a pull request shortly.

```
[2023-01-10 07:52:37] local.WARNING: ErrorException: Creation of dynamic property Yajra\DataTables\EloquentDataTable::$transformer is deprecated in /.../vendor/yajra/laravel-datatables-fractal/src/FractalServiceProvider.php:56
...
[2023-01-10 07:52:37] local.WARNING: ErrorException: Function utf8_encode() is deprecated in /.../vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php:774
```

### PR DESCRIPTION
**Pull request by Naugrimm**
fixes #2930

### CODE REVIEW

File: src/QueryDataTable.php [hunk 1]
```diff
@@ -735,7 +735,7 @@ protected function showDebugger(array $output): array
         $query_log = $this->getConnection()->getQueryLog();
         array_walk_recursive($query_log, function (&$item) {
             if (is_string($item)) {
-                $item = utf8_encode($item);
+                $item = iconv('iso-8859-1', 'utf-8', $item);
```
Comment (yajra) [inline src/QueryDataTable.php:738]: Sorry, not familiar much with ISO. Is this needed/part of the deprecation too? If not, maybe we can separate this into another PR.

Comment (Naugrimm) [reply src/QueryDataTable.php:738]: `utf8_encode` and `utf8_decode` get deprecated in `8.2`. See [here](https://www.php.net/manual/en/function.utf8-encode.php)

The `iconv` call is equivalent to the `utf8_encode` call as per the PHP manual page linked above.

Comment (yajra) [reply src/QueryDataTable.php:738]: thanks for the info, learn something new :)
